cloudify-cosmo/cloudify-rest-docs

README.md
=> Added note about ruby-dev as a requirement

source/includes/_deployments.md, source/includes/_snapshots.md
Can be merged already, if there are no more remarks referring the last section about uploading the snapshot.
=> Initial snapshots docs

source/includes/_events.md
In this PR, the API documentation for the events endpoint is updated to cover version 3, which uses a flat data structure for the items.
=> CFY-6648. Events v3

source/includes/_events.md
In this PR, the `error_causes` field is included in the documentation of the event resource.
=> CFY 6479. Add error causes field to events

source/index.md, source/stylesheets/screen.css.scss
In this PR, a dropdown is added to select the API version.
=> Add api version dropdown v2

make_public.py, source/index.md, source/stylesheets/screen.css.scss
In this PR, a dropdown is added to select the API version.
=> Add api version dropdown v2.1

make_public.py, source/index.md, source/stylesheets/screen.css.scss
In this PR, a dropdown is added to select the API version.
=> Add api version dropdown v3

source/includes/_api.md
In this PR, the examples in the main section (projection, selection, sorting, pagination and authentication) have been updated to v3.
Note: only curl and python examples have been updated. jquery AJAX tab is not maintained and will be removed in a separate PR.
=> CFY 6712. Update basic examples to v3

source/includes/_api.md, source/includes/_blueprints.md, source/includes/_cluster.md, source/includes/_deployments.md, source/includes/_events.md, source/includes/_executions.md, source/includes/_manager.md, source/includes/_node_instances.md, source/includes/_nodes.md, source/includes/_plugins.md, source/includes/_secrets.md, source/includes/_snapshots.md, source/includes/_tenants.md, source/includes/_tokens.md, source/includes/_user_group.md, source/includes/_users.md, source/index.md
In this PR, the javascript examples have been removed since the haven't been maintained. The remaining tabs (curl and python) will be updated in future PRs.
=> CFY 6712. Remove javascript tab

source/includes/_blueprints.md
In this PR, the blueprints section examples are updated to v3.
=> CFY 6712. Update blueprints section to v3

source/includes/_deployments.md
In this PR, the deployments section is updated to v3.
=> CFY 6712. Update deployments to v3

source/includes/_deployments.md, source/includes/_nodes.md
In this PR, the nodes sections of the API documentation is updated to v3.
=> CFY-6834. Update nodes section to v3

source/includes/_node_instances.md
In this PR, the node instances section is updated to v3
=> CFY-6834. Update node instances section to v3

source/includes/_executions.md, source/includes/_node_instances.md
In this PR, the executions section is updated to v3.
=> CFY-6834. Update executions section to v3

source/includes/_plugins.md
In this PR, the plugins section is updated to v3.
=> CFY-6834. Update plugins section to v3

source/includes/_tokens.md
In this PR, the tokens section is updated to v3.
=> CFY-6834. Update tokens section to v3

source/includes/_plugins.md, source/includes/_snapshots.md
In this PR, the snapshots section is updated to v3
=> CFY-6834. Update snapshots section to v3

source/includes/_manager.md
In this PR, the manager section is updated to v3
=> CFY-6834. Update manager section to v3

source/includes/_users.md
In this PR, the role names in the API documentation are updated to the new values.
=> CFY-7350. Update available role names

source/includes/_tenants.md
In this PR, the documentation for the endpoint to add a user a tenant is updated to add the new role parameters.
=> CFY-7350. Add user to tenant with role

source/includes/_tenants.md
In this PR the documentation for the add group to tenant endpoint is updated to take into account the new role parameter.
=> CFY-7373. Add group to tenant with role

source/includes/_tenants.md
In this PR, the REST client examples are updated to include the new role parameter.
In addition to this:
- curl examples are broken into multiple lines for better readability
- output examples are updated to follow the new API behavior (return element count instead of list of elements).
=> CFY-7373. Update REST client examples

source/includes/_tenants.md
In this PR, the documentation for the endpoint to update the user-tenant relationship is added.
In addition to this, the tenants section has been reviewed and new examples using the requests library have been added.
=> CFY-7350. Update user in tenant

source/includes/_tenants.md
In this PR, a new section to explain how to update a user group in tenant is added.
In addition to this, other tenant user group relationship examples are updated to include an example with the python requests library.
=> CFY-7373. Update group tenant

source/includes/_user_group.md
In this PR, the User Groups section is updated to include `_get_data` flag examples.
=> CFY-6412. Add user group examples using get data flag

source/includes/_tenants.md, source/includes/_users.md
In this PR, the Users section is updated to to include `_get_data` flag examples.
=> CFY-6412. Add examples using _get_data flag to Users section

.gitignore, content/_executions.md
Adding docs about ended_at field of execution.
Added Idea folder in git ignore
=> CY-381:  Adding docs about execution resource change.

content/_blueprints.md
Update blueprints documentation with a "Validate Blueprint" section.
=> CY-2363 Add a "validate blueprint" REST endpoint

content/_blueprints.md, content/_cluster.md, content/_deployments.md, content/_operations.md, content/_plugins.md, content/_secrets.md, content/_sites.md, content/_snapshots.md, content/_tenants.md, content/_user_group.md, content/_users.md
Most DELETE calls return a 204-no-content response now.
There is a few exceptions: deleting events and executions
still returns the counts, as before.
This is about the DELETE changes done in CY-3420.
=> CY-3535 DELETE calls return 204

content/_blueprints.md, content/_deployments.md
* Fixing pagination in _deployments.md
* Adding blueprints labels docs
=> Adding blueprints labels docs (#142)

content/_deployment_groups.md, content/_execution_groups.md, content/_executions.md
=> RD-1266 Deployment/execution groups REST docs

content/_execution_groups.md
rest-docs for that new feature
=> RD-1419 Exec-groups: set target success/failure groups

content/_permissions.md
The endpoints for editing permissions assinged to roles
=> RD-1056 Rest docs for permissions

content/_searches.md
Added in cloudify-cosmo/cloudify-manager#3579
=> RD-4468 Deployment searches: also declare installation_status filter

content/_searches.md
* node-instances
* scaling-groups
=> RD-4696 Document new search endpoints

content/_execution_groups.md
This is how to change concurrency for a group.
=> RD-7042 Note about execution-groups set_concurrency
